main: me.theshermantanker.megawalls.MegaWallsPlugin
author: TheShermanTanker
name: MegaWalls
version: 2.0
depend: [WitherCraft]

commands:
  surface:
    description: Teleports Players to the surface